# Alacritty Configuration with Matugen Colors
# Based on user's existing configuration with dynamic color theming

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[terminal]
[colors.primary]
background = '#111318'
foreground = '#e1e2e9'

[colors.selection]
text = '#e1e2e9'
background = '#226ebc'

[colors.cursor]
text = '#111318'
cursor = '#a4c9ff'

[colors.normal]
black   = '#111318'
red     = '#e64c46'
green   = '#70d66e'
yellow  = '#dbd17b'
blue    = '#5582c6'
magenta = '#889ebf'
cyan    = '#a4c9ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f5f'
green   = '#87e086'
yellow  = '#e8df97'
blue    = '#afd7ff'
magenta = '#4a7fa5'
cyan    = '#6578ac'
white   = '#ffffff'

[cursor]
blink_interval = 700
blink_timeout = 5
style = { shape = "Block", blinking = "On" }

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 20
y = 0
