# Alacritty Configuration with Matugen Colors
# Based on user's existing configuration with dynamic color theming

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[terminal]
[colors.primary]
background = '#0f1417'
foreground = '#dee3e7'

[colors.selection]
text = '#dee3e7'
background = '#09b1e1'

[colors.cursor]
text = '#0f1417'
cursor = '#67d3ff'

[colors.normal]
black   = '#0f1417'
red     = '#e64c4c'
green   = '#74d66e'
yellow  = '#dbce7b'
blue    = '#2590bc'
magenta = '#64a4bf'
cyan    = '#67d3ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f64'
green   = '#8be086'
yellow  = '#e8dd97'
blue    = '#6de2ff'
magenta = '#2e8c99'
cyan    = '#4e7ea2'
white   = '#ffffff'

[cursor]
blink_interval = 700
blink_timeout = 5
style = { shape = "Block", blinking = "On" }

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 20
y = 0
