# Alacritty Configuration with Matugen Colors
# Based on user's existing configuration with dynamic color theming

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[terminal]
[colors.primary]
background = '#101415'
foreground = '#dfe3e4'

[colors.selection]
text = '#dfe3e4'
background = '#75cfdd'

[colors.cursor]
text = '#101415'
cursor = '#92ebfa'

[colors.normal]
black   = '#101415'
red     = '#e64c4e'
green   = '#76d66e'
yellow  = '#dbcc7b'
blue    = '#47a8b8'
magenta = '#7db2bb'
cyan    = '#92ebfa'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f66'
green   = '#8ce086'
yellow  = '#e8db97'
blue    = '#8ce1f0'
magenta = '#3b9591'
cyan    = '#4e8093'
white   = '#ffffff'

[cursor]
blink_interval = 700
blink_timeout = 5
style = { shape = "Block", blinking = "On" }

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 20
y = 0
