# Alacritty Configuration with Matugen Colors
# Based on user's existing configuration with dynamic color theming

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[terminal]
[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#8689db'

[colors.cursor]
text = '#131318'
cursor = '#c0c1ff'

[colors.normal]
black   = '#131318'
red     = '#e24e43'
green   = '#6ed671'
yellow  = '#dbd67b'
blue    = '#7a73e9'
magenta = '#999abf'
cyan    = '#c0c1ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0655f'
green   = '#86e088'
yellow  = '#e8e397'
blue    = '#cecfff'
magenta = '#6773c2'
cyan    = '#7a6fbb'
white   = '#ffffff'

[cursor]
blink_interval = 700
blink_timeout = 5
style = { shape = "Block", blinking = "On" }

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 20
y = 0
