# Alacritty Configuration with Matugen Colors
# Based on user's existing configuration with dynamic color theming

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[terminal]
[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'

[colors.selection]
text = '#dee3e6'
background = '#34b1d0'

[colors.cursor]
text = '#0f1416'
cursor = '#62d5f5'

[colors.normal]
black   = '#0f1416'
red     = '#e64c4d'
green   = '#75d66e'
yellow  = '#dbcd7b'
blue    = '#2494b4'
magenta = '#5fa4b7'
cyan    = '#62d5f5'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f65'
green   = '#8be086'
yellow  = '#e8dc97'
blue    = '#67e4ff'
magenta = '#2c8e92'
cyan    = '#4c7f9c'
white   = '#ffffff'

[cursor]
blink_interval = 700
blink_timeout = 5
style = { shape = "Block", blinking = "On" }

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 20
y = 0
