[colors.primary]
background = '#0e1417'
foreground = '#dee3e7'

[colors.selection]
text = '#dee3e7'
background = '#12b8e9'

[colors.cursor]
text = '#0e1417'
cursor = '#66d3ff'

[colors.normal]
black   = '#0e1417'
red     = '#e64c4c'
green   = '#74d66e'
yellow  = '#dbce7b'
blue    = '#2591bc'
magenta = '#63a4bf'
cyan    = '#66d3ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f64'
green   = '#8be086'
yellow  = '#e8dd97'
blue    = '#6ce2ff'
magenta = '#2e8d99'
cyan    = '#4e7ea2'
white   = '#ffffff'
