[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#8689db'

[colors.cursor]
text = '#131318'
cursor = '#c0c1ff'

[colors.normal]
black   = '#131318'
red     = '#e24e43'
green   = '#6ed671'
yellow  = '#dbd67b'
blue    = '#7a73e9'
magenta = '#999abf'
cyan    = '#c0c1ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0655f'
green   = '#86e088'
yellow  = '#e8e397'
blue    = '#cecfff'
magenta = '#6773c2'
cyan    = '#7a6fbb'
white   = '#ffffff'
