format = """
[](#101415)\
$python\
$username\
[](bg:#181c1d fg:#101415)\
$directory\
[](fg:#181c1d bg:#1c2021)\
$git_branch\
$git_status\
[](fg:#1c2021 bg:#ffd5b9)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#ffd5b9 bg:#ffb074)\
$docker_context\
[](fg:#ffb074 bg:#75cfdd)\
$time\
[ ](fg:#75cfdd)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#101415"
style_root = "bg:#101415"
format = '[󰣇 ]($style)'

[directory]
style = "bg:#181c1d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#ffb074"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#1c2021"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#1c2021"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#101415"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#ffd5b9"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#75cfdd"
format = '[ $time ]($style)'
