format = """
[](#0e1417)\
$python\
$username\
[](bg:#171c1f fg:#0e1417)\
$directory\
[](fg:#171c1f bg:#1b2023)\
$git_branch\
$git_status\
[](fg:#1b2023 bg:#e6b4ff)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#e6b4ff bg:#d092f1)\
$docker_context\
[](fg:#d092f1 bg:#12b8e9)\
$time\
[ ](fg:#12b8e9)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#0e1417"
style_root = "bg:#0e1417"
format = '[󰣇 ]($style)'

[directory]
style = "bg:#171c1f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#d092f1"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#1b2023"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#1b2023"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#0e1417"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#e6b4ff"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#12b8e9"
format = '[ $time ]($style)'
