format = """
[](#111318)\
$python\
$username\
[](bg:#191c21 fg:#111318)\
$directory\
[](fg:#191c21 bg:#1d2025)\
$git_branch\
$git_status\
[](fg:#1d2025 bg:#ffb77f)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#ffb77f bg:#a65800)\
$docker_context\
[](fg:#a65800 bg:#226ebc)\
$time\
[ ](fg:#226ebc)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#111318"
style_root = "bg:#111318"
format = '[󰣇 ]($style)'

[directory]
style = "bg:#191c21"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#a65800"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#1d2025"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#1d2025"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#111318"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#ffb77f"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#226ebc"
format = '[ $time ]($style)'
