format = """
[]({{colors.background.default.hex}})\
$python\
$username\
[](bg:{{colors.surface_container_low.default.hex}} fg:{{colors.background.default.hex}})\
$directory\
[](fg:{{colors.surface_container_low.default.hex}} bg:{{colors.surface_container.default.hex}})\
$git_branch\
$git_status\
[](fg:{{colors.surface_container.default.hex}} bg:{{colors.tertiary.default.hex}})\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:{{colors.tertiary.default.hex}} bg:{{colors.tertiary_container.default.hex}})\
$docker_context\
[](fg:{{colors.tertiary_container.default.hex}} bg:{{colors.primary_container.default.hex}})\
$time\
[ ](fg:{{colors.primary_container.default.hex}})\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:{{colors.background.default.hex}}"
style_root = "bg:{{colors.background.default.hex}}"
format = '[󰣇 ]($style)'

[directory]
style = "bg:{{colors.surface_container_low.default.hex}}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:{{colors.tertiary_container.default.hex}}"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:{{colors.surface_container.default.hex}}"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:{{colors.surface_container.default.hex}}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:{{colors.background.default.hex}}"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:{{colors.tertiary.default.hex}}"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:{{colors.primary_container.default.hex}}"
format = '[ $time ]($style)'
